import { motion } from 'framer-motion';
import { ArrowLeft } from 'lucide-react';
import { Link } from 'react-router-dom';
import Footer from '../components/layout/Footer';

export default function Terms() {
  return (
    <div className="min-h-screen bg-dark-bg flex flex-col">
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.4 }}
        className="max-w-4xl mx-auto w-full py-12 sm:py-16 px-5 sm:px-8 flex-1"
      >
        <Link to="/" className="inline-flex items-center gap-1.5 text-sm text-text-muted hover:text-text-primary transition-colors mb-8">
          <ArrowLeft size={16} /> Back
        </Link>

        <h1 className="text-3xl sm:text-4xl font-bold text-text-primary mb-2">Terms & Conditions</h1>
        <p className="text-text-muted text-sm mb-10">Last updated: March 2026</p>

        <div className="space-y-8">
          <section>
            <h2 className="text-xl font-semibold text-text-primary mt-6 mb-3">1. Eligibility</h2>
            <p className="text-text-secondary leading-relaxed">
              You must be at least 13 years of age to use GymThozhan. By creating an account, you confirm that you meet this age requirement. Users under 18 should have parental or guardian consent before using the application.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-text-primary mt-6 mb-3">2. Account Responsibility</h2>
            <p className="text-text-secondary leading-relaxed">
              You are responsible for maintaining the security of your account and all activities that occur under it. GymThozhan uses Google OAuth for authentication — ensure your Google account is secure. You agree to provide accurate information during onboarding.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-text-primary mt-6 mb-3">3. Subscriptions & Payments</h2>
            <p className="text-text-secondary leading-relaxed">
              GymThozhan offers a free tier and a PRO subscription. PRO subscriptions are billed through Razorpay on a monthly or yearly basis. By subscribing, you authorize recurring charges until you cancel. Prices are displayed in INR and may be subject to applicable taxes.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-text-primary mt-6 mb-3">4. Acceptable Use</h2>
            <p className="text-text-secondary leading-relaxed">
              You agree not to misuse the service, including but not limited to: attempting to access other users' data, reverse-engineering the application, using automated tools to scrape content, or distributing workout/diet plans generated by the app for commercial purposes without authorization.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-text-primary mt-6 mb-3">5. Limitation of Liability</h2>
            <p className="text-text-secondary leading-relaxed">
              GymThozhan is provided "as is" without warranties of any kind. We are not liable for any injuries, health issues, or damages arising from the use of workout plans, diet recommendations, or any other content provided through the application. Always consult a healthcare professional before starting any fitness program.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-text-primary mt-6 mb-3">6. Termination</h2>
            <p className="text-text-secondary leading-relaxed">
              We reserve the right to suspend or terminate accounts that violate these terms. You may delete your account and data at any time through the Profile page. Upon termination, your right to use the service ceases immediately.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-text-primary mt-6 mb-3">7. Changes to Terms</h2>
            <p className="text-text-secondary leading-relaxed">
              We may modify these terms at any time. Continued use of GymThozhan after changes constitutes acceptance. We recommend reviewing these terms periodically.
            </p>
          </section>
        </div>
      </motion.div>
      <Footer />
    </div>
  );
}
